### PR TITLE
Proposal to update openstack filter rules

### PR DESCRIPTION
**Pull request by kartoch**
Following issue #44 

- split ETCD rule in two rules (peer-to-peer and client-to-master)
- create cfssl allow rule
- split k8s rules in two rules: k8s_worker and k8s_master

(more to come)

### CODE REVIEW

**Comment by yanndegat** [comment]
hi @kartoch 

thanks a lot , that's great

yet we should remove cfssl port communication
it's mandatory for etcd communication as each node
needs to query etcd for k8s certs or token, 
and etcd requires tls auth from certs generated by cfssl

**Comment by kartoch** [comment]
Thank you @yanndegat . But I cannot identify exactly the relation between cfssl and other parts:

* cfssl is only used during etcd master provisioning ?
* only etcd masters send requests to cfssl node ?

**Comment by yanndegat** [comment]
to communicate with etcd, you need a tls keypair that you can retrieve with a call to cfssl

**Comment by kartoch** [comment]
Has been solved with #54

**Pull request closed without merging**
